name: kdg

services:

  platform_postgres:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: bandit
      POSTGRES_PASSWORD: bandit
      POSTGRES_DB: banditgames
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5544:5432"
    networks:
      - kdg-backend
    volumes:
      - platform_postgres_data:/var/lib/postgresql/data

  chess_postgres:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
      PGDATA: /var/lib/postgresql/data/pgdata
#    ports:
#      - '5443:5432'        # same as teachers, but we don't need them
    networks:
      - kdg-backend
    volumes:
      - ./postgresql/data:/var/lib/postgresql
      - ./init-scripts/sql:/docker-entrypoint-initdb.d

  app_chessgame_back:
    image: registry.gitlab.com/kdg-ti/integration-5/chessgame/back:latest
    # you usually DON'T need to expose port 8080 on host,
    # chess frontend will call it inside the docker network.
    # If you want to debug it directly, you can use 8082:8080 instead.
    # ports:
    #   - '8082:8080'
    platform: linux/amd64
    networks:
      - kdg-backend
    depends_on:
      - chess_postgres
      - app_rabbitmq
    environment:
      - GAME_REGISTRATION_ID=8496c496-a884-48ed-9bb3-7c3aa50fb8ca
      - DATASOURCE_URL=jdbc:postgresql://chess_postgres:5432/postgres
      - DATASOURCE_USER=user
      - DATASOURCE_PASSWORD=password
      - RABBIT_HOST=app_rabbitmq
      - RABBIT_PORT=5672
      - RABBIT_USER=user
      - RABBIT_PASSWORD=password

  app_chessgame_front:
    image: registry.gitlab.com/kdg-ti/integration-5/chessgame/front:latest
    platform: linux/amd64
    depends_on:
      - app_chessgame_back
      - app_rabbitmq
      - chess_postgres
    networks:
      - kdg-backend
    ports:
      - '3333:80'   # you will access chess UI at http://localhost:3333

  gameplay_mongodb:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: gameplay
      MONGO_INITDB_ROOT_USERNAME: user_mongodb
      MONGO_INITDB_ROOT_PASSWORD: password_mongodb
    ports:
      - "27017:27017"
    networks:
      - kdg-backend
    volumes:
      - mongo_data:/data/db
      - ../data/init-scripts/mongo:/docker-entrypoint-initdb.d

  app_rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - kdg-backend
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  idp_mysql:
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - kdg-kc
    volumes:
      - mysql_data:/var/lib/mysql

  idp_keycloak:
    image: quay.io/keycloak/keycloak:26.3
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL_HOST: idp_mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      command: start-dev --import-realm
    depends_on:
      - idp_mysql
    ports:
      - "8180:8080"
    networks:
      - kdg-kc
    volumes:
      - ./realm-export:/opt/keycloak/data/import


networks:
  kdg-kc:
    name: kdg-kc-network
    driver: bridge

  kdg-backend:
    name: kdg-back-network
    driver: bridge

volumes:
  mongo_data:
  rabbitmq_data:
  rabbitmq_logs:
  mysql_data:
  platform_postgres_data:
