image: eclipse-temurin:21-jdk-alpine

stages:
  - build
  - test

before_script:
  - chmod +x backend/gradlew

build_backend:
  stage: build
  script:
    - cd backend
    - ./gradlew clean build

test_backend:
  stage: test
  script:
    - cd backend
    - ./gradlew test
