stages: 
  - build
  - test
    
variables:
  DEFAULT_IMAGE_NAME: eclipse-temurin:21-jdk-alpine
    
build_job:
  stage: build
  image: eclipse-temurin:21-jdk-alpine
  script:
    - echo "Compiling backend using direct Java execution from root..."
    - java -jar gradle/wrapper/gradle-wrapper.jar :backend:clean :backend:build
      
test_job:
  stage: test
  image: eclipse-temurin:21-jdk-alpine
  script:
    - ./gradlew test
      