-- ------------------------------
-- Base schema for BanditGames
-- ------------------------------

-- Achievements table
CREATE TABLE IF NOT EXISTS achievements (
                                            achievement_id UUID NOT NULL PRIMARY KEY,
                                            game_id UUID NOT NULL,
                                            description VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    unlock_hint VARCHAR(255)
    );
--ALTER TABLE achievements OWNER TO bandit;

-- Admins table
CREATE TABLE IF NOT EXISTS admins (
                                      id UUID NOT NULL PRIMARY KEY
);
--ALTER TABLE admins OWNER TO bandit;

-- Event publication table
CREATE TABLE IF NOT EXISTS event_publication (
                                                 id UUID NOT NULL PRIMARY KEY,
                                                 completion_date TIMESTAMP(6) WITH TIME ZONE,
                                                                                  publication_date TIMESTAMP(6) WITH TIME ZONE,
                                                                                  event_type TEXT,
                                                                                  listener_id TEXT,
                                                                                  serialized_event TEXT
                                                                                  );
--ALTER TABLE event_publication OWNER TO bandit;

-- Friendships table
CREATE TABLE IF NOT EXISTS friendships (
                                           id UUID NOT NULL PRIMARY KEY,
                                           created_at TIMESTAMP(6) NOT NULL,
    initiator_id UUID NOT NULL,
    player_a_id UUID NOT NULL,
    player_b_id UUID NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED')),
    UNIQUE (player_a_id, player_b_id)
    );
--ALTER TABLE friendships OWNER TO bandit;

-- Game invitations table
CREATE TABLE IF NOT EXISTS game_invitations (
                                                id UUID NOT NULL PRIMARY KEY,
                                                created_at TIMESTAMP(6) NOT NULL,
    from_player_id UUID NOT NULL,
    to_player_id UUID NOT NULL,
    lobby_id UUID NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELED', 'EXPIRED'))
    );
--ALTER TABLE game_invitations OWNER TO bandit;

-- Games table
CREATE TABLE IF NOT EXISTS games (
                                     id UUID NOT NULL PRIMARY KEY,
                                     description VARCHAR(255),
    name VARCHAR(255),
    picture_url VARCHAR(255),
    rules VARCHAR(255),
    status VARCHAR(255) CHECK (status IN ('DRAFT', 'PUBLISHED', 'REJECTED')),
    url_game_session VARCHAR(255)
    );
--ALTER TABLE games OWNER TO bandit;

-- Lobbies table
CREATE TABLE IF NOT EXISTS lobbies (
                                       id UUID NOT NULL PRIMARY KEY,
                                       game_id UUID,
                                       host_player_id UUID NOT NULL,
                                       guest_player_id UUID,
                                       host_type VARCHAR(255) NOT NULL CHECK (host_type IN ('HUMAN','AI_EASY','AI_MEDIUM','AI_HARD','AI_ML')),
    guest_type VARCHAR(255) CHECK (guest_type IN ('HUMAN','AI_EASY','AI_MEDIUM','AI_HARD','AI_ML')),
    status VARCHAR(255) NOT NULL CHECK (status IN ('WAITING','IN_GAME','FINISHED'))
    );
--ALTER TABLE lobbies OWNER TO bandit;

-- Move recommended projections table
CREATE TABLE IF NOT EXISTS move_recommended_projections (
                                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                            confidence DOUBLE PRECISION NOT NULL,
                                                            move_number INTEGER NOT NULL,
                                                            sessions_id UUID,
                                                            ai_type VARCHAR(255) NOT NULL CHECK (ai_type IN ('HUMAN','AI_EASY','AI_MEDIUM','AI_HARD','AI_ML')),
    recommended_move VARCHAR(255) NOT NULL,
    game_state TEXT NOT NULL,
    legal_moves TEXT NOT NULL
    );
ALTER TABLE move_recommended_projections OWNER TO bandit;

-- Players table
CREATE TABLE IF NOT EXISTS players (
                                       id UUID NOT NULL PRIMARY KEY,
                                       username VARCHAR(255)
    );
--ALTER TABLE players OWNER TO bandit;

-- Player achievements table
CREATE TABLE IF NOT EXISTS player_achievements (
                                                   player_id UUID NOT NULL REFERENCES players(id),
    achievement_id UUID
    );
--ALTER TABLE player_achievements OWNER TO bandit;

-- Player favorite games table
CREATE TABLE IF NOT EXISTS player_favorite_games (
                                                     player_id UUID NOT NULL REFERENCES players(id),
    game_id UUID
    );
--ALTER TABLE player_favorite_games OWNER TO bandit;

-- Win probability projections table
CREATE TABLE IF NOT EXISTS win_probability_projections (
                                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                           move_number INTEGER NOT NULL,
                                                           sessions_id UUID,
                                                           ai_type VARCHAR(255) NOT NULL CHECK (ai_type IN ('HUMAN','AI_EASY','AI_MEDIUM','AI_HARD','AI_ML')),
    player1win_probability DOUBLE PRECISION NOT NULL,
    player2win_probability DOUBLE PRECISION NOT NULL,
    active_player_win_probability DOUBLE PRECISION NOT NULL,
    game_state TEXT NOT NULL,
    legal_moves TEXT NOT NULL
    );
--ALTER TABLE win_probability_projections OWNER TO bandit;

-- Win probability distributions table
CREATE TABLE IF NOT EXISTS win_probability_distributions (
                                                             projection_id BIGINT NOT NULL REFERENCES win_probability_projections(id),
    value TEXT NOT NULL
    );
--ALTER TABLE win_probability_distributions OWNER TO bandit;

-- insert into tables some data
INSERT INTO games (id, name, description, rules, picture_url, status, url_game_session)
VALUES (
           'f2b3aaf4-6db0-4a94-9d82-123456789abc',
           'Connect Four',
           'Classic 2-player connect four game',
           'Connect 4 of your pieces in a row to win.',
           'https://thewashingtonote.com/wp-content/uploads/2023/10/Connect-4-Online-scaled.jpg',
           'DRAFT',
           'http://localhost:8000/connect4/index.html'
       )
    ON CONFLICT (id) DO NOTHING;

INSERT INTO achievements (achievement_id, game_id, name, description, unlock_hint)
VALUES
    ('00000000-0000-0000-0000-000000000011',
     'f2b3aaf4-6db0-4a94-9d82-123456789abc',
     'First Connect',
     'Win your first Connect 4 match on the platform.',
     'Win any Connect 4 match.'),

    ('00000000-0000-0000-0000-000000000012',
     'f2b3aaf4-6db0-4a94-9d82-123456789abc',
     'Vertical Master',
     'Win with a vertical line of four.',
     'Place four of your discs vertically.'),

    ('00000000-0000-0000-0000-000000000013',
     'f2b3aaf4-6db0-4a94-9d82-123456789abc',
     'Diagonal Genius',
     'Win with a diagonal line of four.',
     'Create a diagonal line of four discs.'),

    ('00000000-0000-0000-0000-000000000014',
     'f2b3aaf4-6db0-4a94-9d82-123456789abc',
     'Horizontal Hero',
     'Win with a horizontal line of four.',
     'Place four of your discs horizontally.'),

    ('00000000-0000-0000-0000-000000000015',
     'f2b3aaf4-6db0-4a94-9d82-123456789abc',
     'Speedster',
     'Win the game in under 10 moves.',
     'Achieve victory before either player has placed 10 discs.'),

    ('00000000-0000-0000-0000-000000000016',
     'f2b3aaf4-6db0-4a94-9d82-123456789abc',
     'Late Game Legend',
     'Win after the board is almost full.',
     'Achieve victory when 38 or more discs have been placed.')
    ON CONFLICT (achievement_id) DO NOTHING;
