spring.application.name=banditgames

spring.data.mongodb.database=gameplay
spring.data.mongodb.port=27017
spring.data.mongodb.host=localhost
spring.data.mongodb.username=user_mongodb
spring.data.mongodb.password=password_mongodb

server.port=8083

spring.modulith.events.externalization.enabled=true


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password
spring.rabbitmq.virtual-host=/

# --- PLATFORM POSTGRES (games, achievements, etc.) ---
spring.datasource.url=jdbc:postgresql://localhost:5544/banditgames
spring.datasource.username=bandit
spring.datasource.password=bandit
spring.jpa.hibernate.ddl-auto = update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# -- SECURITY
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/banditgames
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8180/realms/banditgames/protocol/openid-connect/certs


